### PR TITLE
Adding support for logout, issue #7

### PR DESCRIPTION
**Pull request by luksfarris**
Please review if this matches your coding standards, and let me know if I can improve the code quality.
Also, this will need to be improved after https://github.com/openid/AppAuth-iOS/pull/191 is merged

### CODE REVIEW

**Comment by jmelberg-okta** [comment]
Hey @luksfarris! This is awesome! Thanks for taking on this task.

As we're prepping a `1.0.0` release, we're keeping a close eye on your work that was merged into [AppAuth's `dev-logout` branch](https://github.com/openid/AppAuth-iOS/tree/dev-logout). Hopefully that gets merged in with the next AppAuth release.

For us to move forward with this change, can you read over/submit a [CLA](https://developer.okta.com/cla)? Once we have received it, i'll get this merged in!

**Comment by luksfarris** [comment]
Hi @jmelberg-okta , I've just sent the signed CLA to CLA@okta.com
I'm also rebasing the commit to the latest version of branch `dev-0.3.0`.

Would you like me to rebase it to `dev-1.0.0`? Where would you like this pull request to go?

**Comment by jmelberg-okta** [comment]
@luksfarris If you could base this branch off of `dev-1.0.0`, that would be very helpful. We're targeting a `1.0` release by EOM.

**Comment by luksfarris** [comment]
@jmelberg-okta done! It's targeting `dev-1.0.0`. 
Let me know if there's anything else I can help with.
I will continue to work on AppAuth, hopefully we can have a new version soon

**Comment by WillChilcutt** [comment]
Any reason this branch hasn't been merged in? Need to be able to log out but want to get the officially blessed method of doing so. 

Currently all I can do is call `OktaAuth.clear()` but it seems like some credentials are still being cached in the Safari view controller that gets presented as the 2nd time a user logs in (presumably a different user) the safari view controller opens and then immediately closes and auto logs in the first user again.

**Comment by nbarbettini** [comment]
Thanks again for your contributions @luksfarris (and sorry for the long delay).

Since https://github.com/openid/AppAuth-iOS/pull/259 is still open, we decided to fork and get the functionality working in our library in https://github.com/okta/okta-sdk-appauth-ios/pull/103. We are planning to release a new version of this SDK soon that includes the end session (logout) capability.

If you or @WillChilcutt are willing to test it, that would be helpful! You can shoot me an email at nate.barbettini@okta.com.

**Pull request closed without merging**
